# Generated by Django 3.2.5 on 2021-07-03 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthdate',
            new_name='birth_date',
        ),
    ]
