# Generated by Django 3.2.5 on 2021-07-03 06:06

import apps.users.models.users
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_birthdate_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[apps.users.models.users.birt_date_validator], verbose_name='день рождения'),
        ),
    ]
