# Generated by Django 3.2.5 on 2021-07-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
