# Generated by Django 3.2.5 on 2021-07-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offerimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='description',
        ),
        migrations.AddField(
            model_name='offer',
            name='image_url',
            field=models.URLField(default='https://vk.com/', verbose_name='изображение'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OfferImage',
        ),
    ]
