# Generated by Django 3.2.5 on 2021-07-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20210705_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image_url',
            field=models.ImageField(upload_to='offers/images/', verbose_name='изображение'),
        ),
    ]
