# Generated by Django 3.2.5 on 2021-07-05 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offer_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='image_url',
            new_name='image',
        ),
    ]
