# Generated by Django 3.2.5 on 2021-07-20 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_category_id'),
        ('offers', '0005_rename_image_url_offer_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['discount'], 'verbose_name': 'предложение', 'verbose_name_plural': 'предложения'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='services.category'),
        ),
    ]
